# Generated by Django 4.0.5 on 2022-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IEEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
                ('date', models.DateField(verbose_name='date')),
                ('event', models.CharField(choices=[('IN', 'intramural'), ('EX', 'extramural')], default='IN', max_length=2, verbose_name='event')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ('date',),
                'abstract': False,
            },
        ),
    ]
