# Generated by Django 4.0.5 on 2022-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abitur',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('comp_group_id', models.TextField(blank=True, null=True)),
                ('unikey', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('wo_exam', models.IntegerField(blank=True, null=True)),
                ('points_all', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('points_sub', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('points1', models.TextField(blank=True, null=True)),
                ('form_sub1', models.TextField(blank=True, null=True)),
                ('points2', models.TextField(blank=True, null=True)),
                ('form_sub2', models.TextField(blank=True, null=True)),
                ('points3', models.TextField(blank=True, null=True)),
                ('form_sub3', models.TextField(blank=True, null=True)),
                ('points4', models.TextField(blank=True, null=True)),
                ('form_sub4', models.TextField(blank=True, null=True)),
                ('points_id', models.IntegerField(blank=True, null=True)),
                ('att_points', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('passed', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('doc_type', models.TextField(blank=True, null=True)),
                ('soglasie', models.CharField(blank=True, max_length=3, null=True)),
                ('advantage', models.CharField(blank=True, max_length=3, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('cel_org', models.TextField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_group_id', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('comp_group', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('subject', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('priority', models.IntegerField()),
                ('speciality', models.CharField(max_length=255)),
                ('edu_level', models.CharField(max_length=255)),
                ('edu_form', models.CharField(max_length=255)),
                ('finance', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comp_groups',
                'managed': False,
            },
        ),
    ]
