# Generated by Django 4.0.5 on 2022-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='min_mark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='minimal mark'),
        ),
        migrations.AddField(
            model_name='trend',
            name='education_form',
            field=models.CharField(blank=True, max_length=20, verbose_name='education form'),
        ),
        migrations.AddField(
            model_name='trend',
            name='education_level',
            field=models.CharField(blank=True, max_length=128, verbose_name='education level'),
        ),
    ]
